---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - secrets.com.mithung.dev
  resources:
  - supersecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.com.mithung.dev
  resources:
  - supersecrets/finalizers
  verbs:
  - update
- apiGroups:
  - secrets.com.mithung.dev
  resources:
  - supersecrets/status
  verbs:
  - get
  - patch
  - update
