# permissions for end users to edit supersecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: supersecret-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: 2-super-secret-operator
    app.kubernetes.io/part-of: 2-super-secret-operator
    app.kubernetes.io/managed-by: kustomize
  name: supersecret-editor-role
rules:
- apiGroups:
  - secrets.com.mithung.dev
  resources:
  - supersecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.com.mithung.dev
  resources:
  - supersecrets/status
  verbs:
  - get
